# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gao's SB.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.label_about = QtWidgets.QLabel(self.page_about)
        self.label_about.setGeometry(QtCore.QRect(20, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_about.setFont(font)
        self.label_about.setObjectName("label_about")
        self.label_2 = QtWidgets.QLabel(self.page_about)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 741, 421))
        self.label_2.setObjectName("label_2")
        self.stackedWidget_main.addWidget(self.page_about)
        self.page_alignQuery = QtWidgets.QWidget()
        self.page_alignQuery.setObjectName("page_alignQuery")
        self.label_subject = QtWidgets.QLabel(self.page_alignQuery)
        self.label_subject.setGeometry(QtCore.QRect(150, 0, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_subject.setFont(font)
        self.label_subject.setObjectName("label_subject")
        self.label_query = QtWidgets.QLabel(self.page_alignQuery)
        self.label_query.setGeometry(QtCore.QRect(550, -6, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_query.setFont(font)
        self.label_query.setObjectName("label_query")
        self.textEdit_alignmentDestination = QtWidgets.QTextEdit(self.page_alignQuery)
        self.textEdit_alignmentDestination.setGeometry(QtCore.QRect(170, 440, 241, 31))
        self.textEdit_alignmentDestination.setObjectName("textEdit_alignmentDestination")
        self.label = QtWidgets.QLabel(self.page_alignQuery)
        self.label.setGeometry(QtCore.QRect(20, 440, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_doAligning = QtWidgets.QPushButton(self.page_alignQuery)
        self.pushButton_doAligning.setGeometry(QtCore.QRect(430, 440, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_doAligning.setFont(font)
        self.pushButton_doAligning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_doAligning.setCheckable(True)
        self.pushButton_doAligning.setObjectName("pushButton_doAligning")
        self.splitter = QtWidgets.QSplitter(self.page_alignQuery)
        self.splitter.setGeometry(QtCore.QRect(21, 51, 741, 361))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.textEdit_subject = QtWidgets.QTextEdit(self.splitter)
        self.textEdit_subject.setObjectName("textEdit_subject")
        self.textEdit_query = QtWidgets.QTextEdit(self.splitter)
        self.textEdit_query.setObjectName("textEdit_query")
        self.stackedWidget_main.addWidget(self.page_alignQuery)
        self.page_downloadSeq = QtWidgets.QWidget()
        self.page_downloadSeq.setObjectName("page_downloadSeq")
        self.textEdit_accessionList = QtWidgets.QTextEdit(self.page_downloadSeq)
        self.textEdit_accessionList.setGeometry(QtCore.QRect(10, 130, 381, 401))
        self.textEdit_accessionList.setObjectName("textEdit_accessionList")
        self.label_accessionList = QtWidgets.QLabel(self.page_downloadSeq)
        self.label_accessionList.setGeometry(QtCore.QRect(10, 20, 641, 111))
        self.label_accessionList.setObjectName("label_accessionList")
        self.label_3 = QtWidgets.QLabel(self.page_downloadSeq)
        self.label_3.setGeometry(QtCore.QRect(420, 200, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_downloadSeqDestination = QtWidgets.QTextEdit(self.page_downloadSeq)
        self.textEdit_downloadSeqDestination.setGeometry(QtCore.QRect(420, 240, 221, 31))
        self.textEdit_downloadSeqDestination.setObjectName("textEdit_downloadSeqDestination")
        self.pushButton_doDownloadSeq = QtWidgets.QPushButton(self.page_downloadSeq)
        self.pushButton_doDownloadSeq.setGeometry(QtCore.QRect(570, 290, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_doDownloadSeq.setFont(font)
        self.pushButton_doDownloadSeq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_doDownloadSeq.setCheckable(True)
        self.pushButton_doDownloadSeq.setObjectName("pushButton_doDownloadSeq")
        self.stackedWidget_main.addWidget(self.page_downloadSeq)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuSequences = QtWidgets.QMenu(self.menubar)
        self.menuSequences.setObjectName("menuSequences")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_queryAligner = QtWidgets.QAction(MainWindow)
        self.action_queryAligner.setObjectName("action_queryAligner")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_downloadSequence = QtWidgets.QAction(MainWindow)
        self.action_downloadSequence.setObjectName("action_downloadSequence")
        self.menuSequences.addAction(self.action_queryAligner)
        self.menuSequences.addAction(self.action_downloadSequence)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSequences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_about.setText(_translate("MainWindow", "About"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">What you\'re using is a toolbox for</span></p><p><span style=\" font-size:18pt;\">bioinformatics works in Dr. Gao\'s lab.</span></p><p><span style=\" font-size:18pt;\">Contributors: </span><a href=\"http://icannotendure.space/\"><span style=\" font-size:22pt; font-weight:600; font-style:italic; text-decoration: underline; color:#0000ff;\">Yu Sun</span></a></p><p><span style=\" font-size:18pt;\">You can choose tools from menu.</span></p></body></html>"))
        self.label_subject.setText(_translate("MainWindow", "Subject"))
        self.label_query.setText(_translate("MainWindow", "Query"))
        self.label.setText(_translate("MainWindow", "Output file:"))
        self.pushButton_doAligning.setText(_translate("MainWindow", "Do!"))
        self.label_accessionList.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Enter list as below:</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Accesion number\\tStart loc\\tEnd loc</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Example (press Tab to insert a tabular):</span></p><p><span style=\" font-size:11pt; font-weight:600;\">NC_005089.1 15354 16299</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Output file"))
        self.pushButton_doDownloadSeq.setText(_translate("MainWindow", "Do!"))
        self.menuSequences.setTitle(_translate("MainWindow", "Sequences"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_queryAligner.setText(_translate("MainWindow", "Align queries"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_downloadSequence.setText(_translate("MainWindow", "Download sequences"))

